# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
import numpy as np

In [6]:
np.random.randint(0, 20, size = (4, 7))

array([[ 4, 10, 12, 18,  3,  0, 12],
       [ 0,  8,  6,  4,  2,  1, 11],
       [ 8, 17,  1, 10, 17,  6,  8],
       [ 7,  1,  9, 11,  6, 16, 11]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [7]:
np.random.randint(0, 10, size = (8, 10))

array([[3, 7, 9, 1, 9, 6, 9, 3, 2, 9],
       [7, 8, 9, 7, 8, 3, 1, 5, 3, 9],
       [1, 4, 2, 3, 9, 4, 1, 5, 4, 1],
       [1, 4, 7, 9, 4, 7, 6, 8, 7, 8],
       [0, 9, 4, 7, 8, 4, 5, 2, 4, 6],
       [6, 1, 2, 9, 6, 8, 1, 9, 0, 2],
       [5, 2, 4, 5, 9, 2, 1, 7, 5, 1],
       [9, 2, 8, 5, 1, 4, 7, 9, 6, 2]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [10]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [9]:
import numpy as np

a = np.loadtxt('minutes_n_ingredients.csv',dtype='int32', delimiter=',', skiprows=1)
print(a[0:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [9]:
column_1 = a[:,0]    # column = столбец
column_2 = a[:,1] 
column_3 = a[:,2]

# второй столбец
avg_column_2 = np.average(column_2)
min_column_2 = np.min(column_2)
max_column_2 = np.max(column_2)
median_column_2 = np.median(column_2)
print('Среднее значение второго столбца = ', avg_column_2, '\nМинимум второго столбца =', min_column_2, '\nМаксимум второго столбца = ', max_column_2, '\nМедиана второго столбца = ', median_column_2)
avg_column_2, min_column_2, max_column_2, median_column_2

Среднее значение второго столбца =  21601.00169 
Минимум второго столбца = 0 
Максимум второго столбца =  2147483647 
Медиана второго столбца =  40.0


(21601.00169, 0, 2147483647, 40.0)

In [10]:
# третий столбец
avg_column_3 = np.average(column_3)
min_column_3 = np.min(column_3)
max_column_3 = np.max(column3)
median_column_3 = np.median(column_3)
print('Среднее значение третьего столбца = ', avg_column_3, '\nМинимум третьего столбца =', min_column_3, '\nМаксимум третьего столбца = ', max_column_3, '\nМедиана третьего столбца = ', median_column_3)

Среднее значение третьего столбца =  9.05528 
Минимум третьего столбца = 1 
Максимум третьего столбца =  39 
Медиана третьего столбца =  9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [11]:
# вариант 1 - выведем только второй столбец
q = np.quantile(column_2, 0.75)
a[:,1] = np.clip(column_2, 0, int(q))
column_2

array([60, 25, 10, ..., 65,  5, 65])

In [6]:
# вариант 2 - выведем все 3 столбца
q = np.quantile(a[:,1], .75)
a[:,1] = np.clip(a[:,1], 0, q)
print(a)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [10]:
print(np.sum(a[:,1]==0))
a[:,1][a[:,1]==0] = 1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [13]:
unique = np.unique(a, axis=1)
len(unique)           


100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [15]:
lst = list(column_3.copy())
unique = list(set(lst))
frequency = {}
for item in unique:
    frequency[item] = lst.count(item)
print("Всего различных значений количества ингридиентов в рецептах датасета = ", len(unique),"\nСколько раз встречаются различные значения количества ингридиентов = ", frequency)

Всего различных значений количества ингридиентов в рецептах датасета =  37 
Сколько раз встречаются различные значения количества ингридиентов =  {1: 13, 2: 926, 3: 2895, 4: 5515, 5: 7913, 6: 9376, 7: 10628, 8: 10951, 9: 10585, 10: 9591, 11: 8297, 12: 6605, 13: 4997, 14: 3663, 15: 2595, 16: 1767, 17: 1246, 18: 790, 19: 573, 20: 376, 21: 217, 22: 161, 23: 105, 24: 69, 25: 50, 26: 28, 27: 16, 28: 16, 29: 12, 30: 12, 31: 3, 32: 1, 33: 2, 34: 1, 35: 3, 37: 1, 39: 1}


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [17]:
ne_bolshe_5 = a[a[:,2] <= 5]
ne_bolshe_5

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [17]:
ratio = []
for k in range(1, len(a)):
    ratio.append(column_3[k]/column_2[k])
print('Максимальное значение всего датасета = ',max(ratio),'\nСреднее количество ингредиентов на одну минуту для каждого рецепта:',*ratio, sep="\n", end="\n\n")

Максимальное значение всего датасета = 
24.0

Среднее количество ингредиентов на одну минуту для каждого рецепта:
0.28
0.6
1.2
0.23333333333333334
0.175
0.5
0.3333333333333333
1.2857142857142858
0.35
0.3076923076923077
0.5833333333333334
0.16923076923076924
0.6
0.2
0.6666666666666666
0.5833333333333334
0.1076923076923077
0.2
0.3
0.8
0.16923076923076924
0.09230769230769231
0.16923076923076924
0.11666666666666667
0.27692307692307694
0.15
0.2222222222222222
0.13846153846153847
0.06153846153846154
0.55
0.1076923076923077
0.13846153846153847
0.16923076923076924
0.23333333333333334
0.16923076923076924
0.16923076923076924
0.25
0.15555555555555556
0.4
0.8
0.16
0.32
0.14545454545454545
2.0
0.07272727272727272
0.4
1.0
0.24
0.4
0.45714285714285713
0.5625
0.5333333333333333
0.3
0.2
0.07692307692307693
0.15384615384615385
0.075
0.4
0.07692307692307693
0.15
1.0
0.046153846153846156
0.1076923076923077
0.7
0.16923076923076924
0.2
0.15384615384615385
0.46153846153846156
0.13846153846153847
0.4
0.4
0.3


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [18]:
top_100 = a.copy()
top_100 = top_100[top_100[:, 1].argsort()[::-1]][:100]
average_100 = np.average(top_100[:,2])
average_100

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [19]:
print('   ID     TIMING  INGREDIENTS')
for m in range(1,11):
    index = np.where(a[:,0] == np.random.choice(column_1))
    print(a[index])

   ID     TIMING  INGREDIENTS
[[316836     45     15]]
[[208448     65     14]]
[[275876     10     11]]
[[196407     42     10]]
[[158948     35      9]]
[[257843     45      8]]
[[224241     65      8]]
[[108113      8      6]]
[[119267     17      4]]
[[475148     55     19]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [20]:
l = 0
for i in range(1,len(a)):
    if column_3[i]<avg_column_3:
        l+=1
print((l/len(a))*100,'%', sep='')

58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [21]:
k=0
c = []
simple = a.copy()
for m in range(0, len(a)):
    if simple[m,1] <= 20 and simple[m,2] <=5:
        c.append(1)
        k+=1
    else:
        c.append(0)
simple = np.column_stack((simple,c))
simple

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [20]:
print(k/len(a)*100,'%', sep='')

9.552%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
# короткие = до 9 мин, стандартные = 10-19 мин, длинные = 20+ мин
# 0 axis: 0 - short, 1 - standart, 2 - long
# 1 axis: индекс рецепта
# 2 axis: id, продолжительность, ингридиенты - характеристтики

In [22]:
short = []
standart = []
long = []
for i in range(0, len(a)):
    if a[i,1] < 10:
        short.append(a[i])
    elif a[i,1] >= 10 and a[i,1] < 20:
        standart.append(a[i])
    elif a[i,1] >= 20:
        long.append(a[i])
m = min(len(short), len(standart), len(long))

# одинаковая макс. длина
standart = standart[:m]
short = short[:m]
long = long[:m]

d3 = np.stack((short,standart,long), axis=0)

# Возьмем ID из третьего длинного рецепта 
d3[2,2,0], long[:5],d3.shape

(157911,
 [array([127244,     60,     16]),
  array([23891,    25,     7]),
  array([157911,     60,     14]),
  array([152828,     40,      7]),
  array([74205,    20,     7])],
 (3, 7588, 3))